fexp_7d_purch_cols = ['HHExpFCer_Purch_MN_7D',
                        'HHExpFTub_Purch_MN_7D',
                        'HHExpFPuls_Purch_MN_7D',
                        'HHExpFVeg_Purch_MN_7D',
                        'HHExpFFrt_Purch_MN_7D',
                        'HHExpFAnimMeat_Purch_MN_7D',
                        'HHExpFAnimFish_Purch_MN_7D',
                        'HHExpFFats_Purch_MN_7D',
                        'HHExpFDairy_Purch_MN_7D',
                        'HHExpFEgg_Purch_MN_7D',
                        'HHExpFSgr_Purch_MN_7D',
                        'HHExpFCond_Purch_MN_7D',
                        'HHExpFBev_Purch_MN_7D',
                        'HHExpFOut_Purch_MN_7D']

fexp_7d_giftaid_cols = ['HHExpFCer_GiftAid_MN_7D',
                        'HHExpFTub_GiftAid_MN_7D',
                        'HHExpFPuls_GiftAid_MN_7D',
                        'HHExpFVeg_GiftAid_MN_7D',
                        'HHExpFFrt_GiftAid_MN_7D',
                        'HHExpFAnimMeat_GiftAid_MN_7D',
                        'HHExpFAnimFish_GiftAid_MN_7D',
                        'HHExpFFats_GiftAid_MN_7D',
                        'HHExpFDairy_GiftAid_MN_7D',
                        'HHExpFEgg_GiftAid_MN_7D',
                        'HHExpFSgr_GiftAid_MN_7D',
                        'HHExpFCond_GiftAid_MN_7D',
                        'HHExpFBev_GiftAid_MN_7D',
                        'HHExpFOut_GiftAid_MN_7D']

fexp_7d_own_cols = ['HHExpFCer_Own_MN_7D',
                    'HHExpFTub_Own_MN_7D',
                    'HHExpFPuls_Own_MN_7D',
                    'HHExpFVeg_Own_MN_7D',
                    'HHExpFFrt_Own_MN_7D',
                    'HHExpFAnimMeat_Own_MN_7D',
                    'HHExpFAnimFish_Own_MN_7D',
                    'HHExpFFats_Own_MN_7D',
                    'HHExpFDairy_Own_MN_7D',
                    'HHExpFEgg_Own_MN_7D',
                    'HHExpFSgr_Own_MN_7D',
                    'HHExpFCond_Own_MN_7D',
                    'HHExpFBev_Own_MN_7D',
                    'HHExpFOut_Own_MN_7D']

fexp_7d_cols = fexp_7d_purch_cols + fexp_7d_giftaid_cols + fexp_7d_own_cols
