columns_type:
  HHDwellType: 'str'
  HHTenureType: 'str'
  HHWallType: 'str'
  HHRoofType: 'str'
  HHFloorType: 'str'

choices_lists:
  HHDwellType:
    - '100'
    - '200'
    - '300'
    - '400'
    - '401'
    - '402'
    - '403'
    - '500'
    - '600'
    - '999'
  HHTenureType:
    - '101'
    - '201'
    - '202'
    - '203'
    - '300'
    - '400'
    - '500'
    - '601'
    - '602'
    - '603'
    - '999'
  HHWallType:
    - '101'
    - '102'
    - '103'
    - '104'
    - '105'
    - '106'
    - '107'
    - '108'
    - '109'
    - '110'
    - '111'
    - '112'
    - '113'
    - '114'
    - '115'
    - '116'
    - '117'
    - '118'
    - '119'
    - '888'
    - '999'
  HHRoofType:
    - '100'
    - '200'
    - '300'
    - '400'
    - '500'
    - '600'
    - '700'
    - '800'
    - '900'
    - '999'
  HHFloorType:
    - '100'
    - '200'
    - '300'
    - '400'
    - '500'
    - '600'
    - '700'
    - '800'
    - '999'
