columns_type:
  Lcs_stress_DomAsset: 'str'
  Lcs_stress_Saving: 'str'
  Lcs_stress_EatOut: 'str'
  Lcs_stress_BorrowCash: 'str'
  Lcs_stress_Pawn: 'str'
  Lcs_stress_LessSchool: 'str'
  Lcs_stress_DomMigration: 'str'
  Lcs_stress_HHSeparation: 'str'
  Lcs_stress_ConsActive: 'str'
  Lcs_stress_Housing: 'str'
  Lcs_stress_Utilities: 'str'
  Lcs_stress_SellFoodRation: 'str'
  Lcs_crisis_ProdAssets: 'str'
  Lcs_crisis_Health: 'str'
  Lcs_crisis_Edu: 'str'
  Lcs_crisis_Housing: 'str'
  Lcs_crisis_HHSeparation: 'str'
  Lcs_crisis_ChildWork: 'str'
  Lcs_crisis_Marriage: 'str'
  Lcs_crisis_Migration: 'str'
  Lcs_crisis_ConsActive: 'str'
  Lcs_crisis_OutSchool: 'str'
  Lcs_crisis_Barter: 'str'
  Lcs_crisis_Utilities: 'str'
  Lcs_em_OutSchool: 'str'
  Lcs_em_Migration: 'str'
  Lcs_em_ChildWork: 'str'
  Lcs_em_Marriage: 'str'
  Lcs_em_ResAsset: 'str'
  Lcs_em_Begged: 'str'
  Lcs_em_IllegalAct: 'str'
  Lcs_em_ChildMigration: 'str'
  Lcs_crisis_DomMigration: 'str'
  Lcs_stress_SellNFIRation: 'str'
  Lcs_stress_Edu: 'str'

choices_lists:
  Lcs_stress_DomAsset:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_stress_Saving:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_stress_EatOut:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_stress_BorrowCash:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_stress_Pawn:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_stress_LessSchool:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_stress_DomMigration:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_stress_HHSeparation:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_stress_ConsActive:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_stress_Housing:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_stress_Utilities:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_stress_SellFoodRation:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_crisis_ProdAssets:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_crisis_Health:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_crisis_Edu:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_crisis_Housing:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_crisis_HHSeparation:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_crisis_ChildWork:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_crisis_Marriage:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_crisis_Migration:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_crisis_ConsActive:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_crisis_OutSchool:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_crisis_Barter:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_crisis_Utilities:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_em_OutSchool:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_em_Migration:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_em_ChildWork:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_em_Marriage:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_em_ResAsset:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_em_Begged:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_em_IllegalAct:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_em_ChildMigration:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_crisis_DomMigration:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_stress_SellNFIRation:
    - '10'
    - '20'
    - '30'
    - '9999'
  Lcs_stress_Edu:
    - '10'
    - '20'
    - '30'
    - '9999'
  
lcs_fs_children_cols:
  - 'Lcs_stress_LessSchool'
  - 'Lcs_crisis_OutSchool'
  - 'Lcs_crisis_ChildWork'
  - 'Lcs_em_ChildMigration'
  - 'Lcs_em_Marriage'

lcs_fs_non_exhaustive_cols:
  - 'Lcs_em_Begged'
  - 'Lcs_em_IllegalAct'
  - 'Lcs_stress_BorrowCash'
