columns_type:
  LcsEN_stress_DomAsset: 'str'
  LcsEN_stress_Saving: 'str'
  LcsEN_stress_BorrowCash: 'str'
  LcsEN_stress_Pawn: 'str'
  LcsEN_stress_Housing: 'str'
  LcsEN_stress_LessSchool: 'str'
  LcsEN_stress_HHSeparation: 'str'
  LcsEN_stress_SellRation: 'str'
  LcsEN_stress_DomMigration: 'str'
  LcsEN_stress_Utilities: 'str'
  LcsEN_stress_Edu: 'str'
  LcsEN_stress_ConsActive: 'str'
  LcsEN_crisis_ProdAssets: 'str'
  LcsEN_crisis_Health: 'str'
  LcsEN_crisis_Edu: 'str'
  LcsEN_crisis_Housing: 'str'
  LcsEN_crisis_HHSeparation: 'str'
  LcsEN_crisis_OutSchool: 'str'
  LcsEN_crisis_Marriage: 'str'
  LcsEN_crisis_Migration: 'str'
  LcsEN_crisis_ChildWork: 'str'
  LcsEN_crisis_ConsActive: 'str'
  LcsEN_crisis_Utilities: 'str'
  LcsEN_crisis_DomMigration: 'str'
  LcsEN_crisis_Barter: 'str'
  LcsEN_em_OutSchool: 'str'
  LcsEN_em_Migration: 'str'
  LcsEN_em_ChildWork: 'str'
  LcsEN_em_Marriage: 'str'
  LcsEN_em_ResAsset: 'str'
  LcsEN_em_Begged: 'str'
  LcsEN_em_IllegalAct: 'str'
  LcsEN_em_ChildMigration: 'str'
  
choices_lists:
  LcsEN_stress_DomAsset:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_stress_Saving:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_stress_BorrowCash:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_stress_Pawn:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_stress_Housing:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_stress_LessSchool:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_stress_HHSeparation:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_stress_SellRation:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_stress_DomMigration:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_stress_Utilities:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_stress_Edu:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_stress_ConsActive:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_crisis_ProdAssets:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_crisis_Health:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_crisis_Edu:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_crisis_Housing:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_crisis_HHSeparation:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_crisis_OutSchool:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_crisis_Marriage:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_crisis_Migration:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_crisis_ChildWork:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_crisis_ConsActive:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_crisis_Utilities:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_crisis_DomMigration:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_crisis_Barter:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_em_OutSchool:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_em_Migration:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_em_ChildWork:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_em_Marriage:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_em_ResAsset:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_em_Begged:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_em_IllegalAct:
    - '10'
    - '20'
    - '30'
    - '9999'
  LcsEN_em_ChildMigration:
    - '10'
    - '20'
    - '30'
    - '9999'
  
lcs_en_children_cols:
  - 'LcsEN_stress_LessSchool'
  - 'LcsEN_crisis_OutSchool'
  - 'LcsEN_crisis_ChildWork'
  - 'LcsEN_em_ChildMigration'
  - 'LcsEN_em_Marriage'

lcs_en_non_exhaustive_cols:
  - 'LcsEN_em_Begged'
  - 'LcsEN_em_IllegalAct'
  - 'LcsEN_stress_BorrowCash'
