used_strategies:
  - 'Lcs_stress_DomAsset'
  - 'Lcs_stress_Saving'
  - 'Lcs_stress_EatOut'
  - 'Lcs_stress_BorrowCash'
  - 'Lcs_crisis_ProdAssets'
  - 'Lcs_crisis_Health'
  - 'Lcs_crisis_Edu'
  - 'Lcs_em_OutSchool'
  - 'Lcs_em_Migration'
  - 'Lcs_em_ChildWork'