# In minutes
short_survey_mins: 20
long_survey_mins: 150

# Adjust according to the timezone of the country office
utc: +1

# Time thresholds to categorize the start time of the survey
time_thresholds:
  early_morning:
    start: "0"
    end: "7"
  morning:
    start: "7"
    end: "12"
  afternoon:
    start: "12"
    end: "19"
  evening:
    start: "19"
    end: "21"
  night:
    start: "21"
    end: "24"

# Categories that seem abnormal for the enumerator to start a survey
abnormal_period:
  - early_morning
  - evening
  - night