abnormal_period:
- early_morning
- evening
- late_evening
invalid_duration: 5
long_duration_mins:  99999999
short_duration_mins: 10
time_thresholds:
  afternoon:
    end: '19'
    start: '12'
  early_morning:
    end: '7'
    start: '0'
  evening:
    end: '21'
    start: '19'
  morning:
    end: '12'
    start: '7'
  night:
    end: '24'
    start: '21'
utc: 2
